title: "Polymat Builds"
description: "Carpentry, DIY, and other physical projects by Mat Warren"
baseurl: "/polymat-builds"   # repo name
url: "https://astro-mat.github.io"

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

# Optional, for clean URLs
permalink: /:title/




