# title: "Polymat Builds"
# description: "Carpentry, DIY, and other physical projects by Mat Warren"
# baseurl: "/polymat-builds"   # repo name
# url: "https://astro-mat.github.io"

# theme: minima


# # Optional, for clean URLs
# permalink: /:title/

title: Polymat Builds
email: whoismatwarren@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Carpentry, DIY, and other physical projects by Mat Warren
baseurl: '/polymat-builds' # the subpath of your site, e.g. /blog
url: 'https://astro-mat.github.io' # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: astro-mat

permalink: /:collection/:year-:month-:day-:title:output_ext
show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-feed