remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
title: "Polymat Builds"
description: "Carpentry, DIY, and other physical projects by Mat Warren"
baseurl: "/polymat-builds"  # your repo name
url: "https://astro-mat.github.io"
permalink: /:title/
