title: "Polymat Builds"
description: "Carpentry, DIY, and other physical projects by Mat Warren"
baseurl: "/polymat-builds"  # repo name
url: "https://astro-mat.github.io"  # GitHub Pages root
theme: minima
permalink: /:title/
