remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Polymat Builds"
description: "Carpentry, DIY, and other physical projects by Mat Warren"
baseurl: "/polymat-builds"  # repo name
url: "https://astro-mat.github.io"  # GitHub Pages root
permalink: /:title/

